### ISSUE TITLE
ovmf build fails

### ISSUE THREAD

**Issue by churkanerusskaya** [AMDESE/ovmf#2]
Hello!

I am trying to compile the components for ses-es using the build script, however I get the same error every time :

<skip>
...

nice build -q --cmd-len=64436 -DDEBUG_ON_SERIAL_PORT=TRUE -n 32 -t GCC5 -a X64 -p OvmfPkg/OvmfPkgX64.dsc
Build environment: Linux-4.15.0-126-generic-x86_64-with-Ubuntu-18.04-bionic
Build start time: 20:55:58, Dec.07 2020

WORKSPACE        = /root/AMDSEV/build/ovmf
EDK_TOOLS_PATH   = /root/AMDSEV/build/ovmf/BaseTools
CONF_PATH        = /root/AMDSEV/build/ovmf/Conf
PYTHON_COMMAND   = /usr/bin/python3.6

Processing meta-data ....... done!
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/XenPlatformLib/XenPlatformLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseOrderedCollectionRedBlackTreeLib/BaseOrderedCollectionRedBlackTreeLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxeServicesTableLib/DxeServicesTableLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/QemuFwCfgS3Lib/DxeQemuFwCfgS3LibFwCfg.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiDriverEntryPoint/UefiDriverEntryPoint.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxeHobLib/DxeHobLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/QemuFwCfgLib/QemuFwCfgDxeLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiLib/UefiLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/BaseMemEncryptSevLib/BaseMemEncryptSevLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiDevicePathLibDevicePathProtocol/UefiDevicePathLibDevicePathProtocol.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiRuntimeServicesTableLib/UefiRuntimeServicesTableLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseCacheMaintenanceLib/BaseCacheMaintenanceLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseCpuLib/BaseCpuLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiMemoryAllocationLib/UefiMemoryAllocationLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiBootServicesTableLib/UefiBootServicesTableLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseDebugLibSerialPort/BaseDebugLibSerialPort.inf [X64]
Building ... /root/AMDSEV/build/ovmf/PcAtChipsetPkg/Library/SerialIoLib/SerialIoLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BasePrintLib/BasePrintLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseDebugPrintErrorLevelLib/BaseDebugPrintErrorLevelLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsicSev.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxePcdLib/DxePcdLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseMemoryLibRepStr/BaseMemoryLibRepStr.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseLib/BaseLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/PeiExtractGuidedSectionLib/PeiExtractGuidedSectionLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseUefiDecompressLib/BaseUefiDecompressLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxeExtractGuidedSectionLib/DxeExtractGuidedSectionLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxeCoreHobLib/DxeCoreHobLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxeCoreEntryPoint/DxeCoreEntryPoint.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdeModulePkg/Library/DxeCoreMemoryAllocationLib/DxeCoreMemoryAllocationLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdeModulePkg/Library/BootLogoLib/BootLogoLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/NvVarsFileLib/NvVarsFileLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/X86QemuLoadImageLib/X86QemuLoadImageLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/QemuBootOrderLib/QemuBootOrderLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/PlatformBmPrintScLib/PlatformBmPrintScLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/Tcg2PhysicalPresenceLibNull/DxeTcg2PhysicalPresenceLib.inf [X64]

build.py...
 : error 7000: Failed to execute command
	make tbuild [/root/AMDSEV/build/ovmf/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/BaseCpuLib/BaseCpuLib]

build.py...
 : error 7000: Failed to execute command
	make tbuild [/root/AMDSEV/build/ovmf/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsicSev]

build.py...
 : error 7000: Failed to execute command
	make tbuild [/root/AMDSEV/build/ovmf/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/BaseMemoryLibRepStr/BaseMemoryLibRepStr]

build.py...
 : error 7000: Failed to execute command
	make tbuild [/root/AMDSEV/build/ovmf/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/BaseLib/BaseLib]

build.py...
 : error F002: Failed to build module
	/root/AMDSEV/build/ovmf/MdePkg/Library/BaseCpuLib/BaseCpuLib.inf [X64, GCC5, DEBUG]

- Failed -
Build end time: 20:56:07, Dec.07 2020
Build total time: 00:00:09

ERROR: nice build -q --cmd-len=64436 -DDEBUG_ON_SERIAL_PORT=TRUE -n 32 -t GCC5 -a X64 -p OvmfPkg/OvmfPkgX64.dsc
root@unibox:~/AMDSEV/build#

I tried differnet OSes with the same result:
Ubuntu 18.04, Debian 10, Centos 7, Centos 8.

I guess that the problem is somewhere in the code of other repositories (probably the code was updated there) used for the build, but where exactly I could not figure out even with Google. Could you please help with this?

Thanks!

**Comment by tlendacky** [comment]
You can get more detailed error information by doing:
`cd ~/AMDSEV/build/ovmf`
`. ./edksetup.sh`
`nice build -q --cmd-len=64436 -DDEBUG_ON_SERIAL_PORT=TRUE -n 32 -t GCC5 -a X64 -p OvmfPkg/OvmfPkgX64.dsc`

**Comment by churkanerusskaya** [comment]
Hello

Thanks for the answer, but no more detail info, unfortunately:

root@unibox:~/AMDSEV/build# cd ovmf/
root@unibox:~/AMDSEV/build/ovmf# . ./edksetup.sh
Loading previous configuration from /root/AMDSEV/build/ovmf/Conf/BuildEnv.sh
WORKSPACE: /root/AMDSEV/build/ovmf
EDK_TOOLS_PATH: /root/AMDSEV/build/ovmf/BaseTools
CONF_PATH: /root/AMDSEV/build/ovmf/Conf
root@unibox:~/AMDSEV/build/ovmf# nice build -q --cmd-len=64436 -DDEBUG_ON_SERIAL_PORT=TRUE -n 32 -t GCC5 -a X64 -p OvmfPkg/OvmfPkgX64.dsc
Build environment: Linux-4.15.0-126-generic-x86_64-with-Ubuntu-18.04-bionic
Build start time: 21:39:27, Dec.07 2020

WORKSPACE        = /root/AMDSEV/build/ovmf
EDK_TOOLS_PATH   = /root/AMDSEV/build/ovmf/BaseTools
CONF_PATH        = /root/AMDSEV/build/ovmf/Conf
PYTHON_COMMAND   = /usr/bin/python3.6

Processing meta-data ...... done!
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/XenPlatformLib/XenPlatformLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseOrderedCollectionRedBlackTreeLib/BaseOrderedCollectionRedBlackTreeLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxeServicesTableLib/DxeServicesTableLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/QemuFwCfgS3Lib/DxeQemuFwCfgS3LibFwCfg.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiDriverEntryPoint/UefiDriverEntryPoint.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxeHobLib/DxeHobLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/QemuFwCfgLib/QemuFwCfgDxeLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiLib/UefiLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/BaseMemEncryptSevLib/BaseMemEncryptSevLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiDevicePathLibDevicePathProtocol/UefiDevicePathLibDevicePathProtocol.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiRuntimeServicesTableLib/UefiRuntimeServicesTableLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseCacheMaintenanceLib/BaseCacheMaintenanceLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseCpuLib/BaseCpuLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiMemoryAllocationLib/UefiMemoryAllocationLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/UefiBootServicesTableLib/UefiBootServicesTableLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseDebugLibSerialPort/BaseDebugLibSerialPort.inf [X64]
Building ... /root/AMDSEV/build/ovmf/PcAtChipsetPkg/Library/SerialIoLib/SerialIoLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BasePrintLib/BasePrintLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseDebugPrintErrorLevelLib/BaseDebugPrintErrorLevelLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsicSev.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxePcdLib/DxePcdLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseMemoryLibRepStr/BaseMemoryLibRepStr.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseLib/BaseLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/PeiExtractGuidedSectionLib/PeiExtractGuidedSectionLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/BaseUefiDecompressLib/BaseUefiDecompressLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxeExtractGuidedSectionLib/DxeExtractGuidedSectionLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxeCoreHobLib/DxeCoreHobLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdePkg/Library/DxeCoreEntryPoint/DxeCoreEntryPoint.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdeModulePkg/Library/DxeCoreMemoryAllocationLib/DxeCoreMemoryAllocationLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/MdeModulePkg/Library/BootLogoLib/BootLogoLib.inf [X64]
Building ... /root/AMDSEV/build/ovmf/OvmfPkg/Library/NvVarsFileLib/NvVarsFileLib.inf [X64]


build.py...
 : error 7000: Failed to execute command
	make tbuild [/root/AMDSEV/build/ovmf/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/BaseCpuLib/BaseCpuLib]


build.py...
 : error 7000: Failed to execute command
	make tbuild [/root/AMDSEV/build/ovmf/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsicSev]


build.py...
 : error 7000: Failed to execute command
	make tbuild [/root/AMDSEV/build/ovmf/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/BaseMemoryLibRepStr/BaseMemoryLibRepStr]


build.py...
 : error 7000: Failed to execute command
	make tbuild [/root/AMDSEV/build/ovmf/Build/OvmfX64/DEBUG_GCC5/X64/MdePkg/Library/BaseLib/BaseLib]


build.py...
 : error F002: Failed to build module
	/root/AMDSEV/build/ovmf/MdePkg/Library/BaseCpuLib/BaseCpuLib.inf [X64, GCC5, DEBUG]

- Failed -
Build end time: 21:39:34, Dec.07 2020
Build total time: 00:00:07

root@unibox:~/AMDSEV/build/ovmf#

**Comment by tlendacky** [comment]
Try removing the -q and adding -v to the build command and see if that helps.

**Comment by churkanerusskaya** [comment]
-v is much more informative - iasl&nasm were missing.  I would never have guessed.
Thanks a lot!
